name: riderapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  gradients: ^0.1.1+2
  firebase_storage: ^11.0.15
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  firebase_auth: ^4.2.10
  scaffold_gradient_background: ^1.0.3+1
  camera: ^0.9.4+19
  flutter_easyloading: ^3.0.5
  hive_flutter: ^1.1.0
  quickalert: ^1.0.1
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^1.4.0
  shared_preferences: ^2.0.7
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  google_maps_flutter: ^2.1.3
  location: ^4.3.0
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  web_socket_channel: ^2.4.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/ca/
  

  